apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogs-api
  namespace: logging
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: blogs-api
  template:
    metadata:
       labels:
         app: blogs-api
    spec:
      containers:
       - name: blogs-api
         image: rmanimaran/dotnetk8s:latest
         ports:
          - containerPort: 8080
          - containerPort: 8081
         env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"
          - name: ASPNETCORE_URLS
            value: "http://+:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: blogs-api-service
  namespace: logging
spec:
  selector:
    app: blogs-api
  ports:
  - name: http
    port: 5000
    targetPort: 8080
  - name: https
    port: 5001
    targetPort: 8081
  type: LoadBalancer