# kibana-values.yaml
elasticsearchHosts: "http://elasticsearch-master:9200"

resources:
  requests:
    cpu: "100m"
    memory: "500Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

service:
  type: LoadBalancer
  port: 5601

kibanaConfig:
  kibana.yml: |
    server.name: kibana
    server.host: "0.0.0.0"
