apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
      - name: fastapi-app
        image: rmanimaran/fastapi-monitoring:v2 
        ports:
        - containerPort: 7755
          name: web

