apiVersion: v1
kind: Service
metadata:
  name: fastapi-app
  namespace: monitoring
  labels:
    app: fastapi-app
spec:
  selector:
    app: fastapi-app
  ports:
  - port: 7755
    targetPort: 7755
    name: web