apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: sidecar-tracing
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/app/*.log
      pos_file /var/log/fluentd/app.pos
      tag app.*
      <parse>
        @type json
        time_key timestamp
      </parse>
    </source>
    <match app.**>
      @type stdout 
      <server>
        host fluentd-aggregator
        port 24224
      </server>
    </match>