apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracingapp-deployment
  namespace: sidecar-tracing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tracingapp-deployment
  template:
    metadata:
      labels:
        app: tracingapp-deployment
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9090"
    spec:
      volumes:
        - name: log-volume
          emptyDir: {}
        - name: fluentd-config
          configMap:
            name: fluentd-config
    
      containers:
        # Application Container
      - name: ecommerce-api
        image: rmanimaran/ecommercesidecartraceapp:1.0.0
        ports:
        - containerPort: 8080
        - containerPort: 9090  # Prometheus Port
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        volumeMounts:
        - name: log-volume
          mountPath: /var/log/app
        resources:
          requests: { cpu: "100m", memory: "128Mi" }
          limits: { cpu: "500m", memory: "256Mi" }
        livenessProbe:
          httpGet: {path: "/healthz/ready", port: 8080}
          initialDelaySeconds: 5
          periodSeconds: 10
      
      # Fluentd Sidecar Container
      - name: fluentd-sidecar
        image: fluent/fluentd:v1.16-1
        volumeMounts:
        - name: fluentd-config
          mountPath: /fluentd/etc
        - name: log-volume
          mountPath: /var/log/app
        resources:
          requests: { cpu: "50m", memory: "64Mi" }
          limits: { cpu: "100m", memory: "128Mi" }

      # Prometheus Exporter Sidecar Container
      - name: prometheus-exporter
        image: prom/prometheus:v2.48.0
        args:
          - "--config.file=/etc/prometheus/prometheus.yml"
        resources:
          requests: { cpu: "50m", memory: "64Mi" }
          limits: { cpu: "100m", memory: "128Mi" }