apiVersion: apps/v1
kind: Deployment

metadata:
  name: customer-app
  namespace: app-communication

spec:
  replicas: 1

  selector:
    matchLabels:
      app: customer-app
  template:
    metadata:
      labels:
        app: customer-app
    spec:
      containers:
        - name: customer-app
          image: maranecr.azurecr.io/customer-app:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          
