apiVersion: v1
kind: Service
metadata:
  name: customer-api
  namespace: app-communication
spec:
  type: LoadBalancer
  selector:
    app: customer-api
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
