apiVersion: v1
kind: Service
metadata:
  name: azure-function-service
  namespace: logging
spec:
  selector:
    app: az-func-imageUploader
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer