apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-file-logging-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  storageClassName: azurefile-logs-file
  accessModes:
    - ReadWriteMany
